apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-websockets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-websockets
  template:
    metadata:
      labels:
        app: go-websockets
    spec:
      containers:
        - name: go-websockets
          image: noahdev123/go-websockets
          ports:
            - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: go-websockets-service
  labels:
    app: go-websockets
spec:
  selector:
    app: go-websockets
  ports:
  - name: websocket
    protocol: TCP
    port: 4001
    targetPort: 4001
  type: LoadBalancer