apiVersion: v1
kind: Deployment
metadata:
  name: go-websockets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-websockets
  template:
    metadata:
      labels:
        app: go-websockets
    spec:
      containers:
        - name: go-websockets
          image: noahwilderom/go-websockets
          ports:
            - containerPort: 4001